version: '3.8'
services:
  scraper:
    image: bartczaktech/scraper:${IMAGE_TAG}
    restart: always
    volumes:
      - json_files:/app/json_files
      - ./logs:/app/logs

  api:
    image: bartczaktech/api:${IMAGE_TAG}
    restart: always
    volumes:
      - json_files:/app/json_files
      - ./logs:/app/logs
    ports:
      - "8000:8000"

volumes:
  json_files: