version: '3.8'
services:
  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    volumes:
      - json_files:/app/json_files

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - json_files:/app/json_files
    ports:
      - "8000:8000"

volumes:
  json_files:
