version: '3.8'
services:
  scraper:
    image: bartczaktech/scraper:latest
    build:
      context: .
      dockerfile: scraper/Dockerfile
    volumes:
      - json_files:/app/json_files
      - ./logs:/app/logs

  api:
    image: bartczaktech/api:latest
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - json_files:/app/json_files
      - ./logs:/app/logs
    ports:
      - "8000:8000"

volumes:
  json_files: